In [24]:
#word_index


import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

# Define the texts
texts = ['I like girls, I love parrots', 'I love humans being!']

# Create a Tokenizer
tokenizer = Tokenizer()

# Fit the tokenizer to the texts
tokenizer.fit_on_texts(texts)

# Convert the texts to word indices
word_index = tokenizer.word_index

# Convert the texts to sequences
sequences = tokenizer.texts_to_sequences(texts)

print("Word Index:")
print(word_index)
print("\nSequences:")
print(sequences)


#This code defines two texts, creates a Tokenizer, fits it to the texts, converts the texts to word indices, and then converts the texts to sequences. The word index and sequences are then printed out.

Word Index:
{'i': 1, 'love': 2, 'like': 3, 'girls': 4, 'parrots': 5, 'humans': 6, 'being': 7}

Sequences:
[[1, 3, 4, 1, 2, 5], [1, 2, 6, 7]]


In [25]:
#pad_sequences


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Define the texts
texts = ['I like dog', 'I love cat', 'I love human being']
test_texts = ['I like dog', 'I don\'t like cat', 'I like parents', 'I don\'t like dog, eats & parrots']

# Create a Tokenizer
tokenizer = Tokenizer(num_words=100, oov_token='[UNK]')

# Fit the tokenizer to the texts
tokenizer.fit_on_texts(texts)

# Convert the texts to word indices
word_index = tokenizer.word_index

# Convert the texts to sequences
sequences = tokenizer.texts_to_sequences(texts)

# Convert the test texts to sequences
test_sequences = tokenizer.texts_to_sequences(test_texts)

# Pad the sequences
padded_sequences = pad_sequences(sequences, padding='pre', maxlen=20, truncating='post')
padded_test_sequences = pad_sequences(test_sequences, padding='pre', maxlen=20, truncating='post')

print("Word Index:")
print(word_index)
print("\nSequences:")
print(sequences)
print("\nTest Sequences:")
print(test_sequences)
print("\nPadded Sequences:")
print(padded_sequences)
print("\nPadded Test Sequences:")
print(padded_test_sequences)


#This code defines two sets of texts, creates a Tokenizer, fits it to the first set of texts, converts the texts to word indices, converts the texts to sequences, and then pads the sequences to a maximum length of 20. The word index, sequences, test sequences, padded sequences, and padded test sequences are then printed out.

Word Index:
{'[UNK]': 1, 'i': 2, 'love': 3, 'like': 4, 'dog': 5, 'cat': 6, 'human': 7, 'being': 8}

Sequences:
[[2, 4, 5], [2, 3, 6], [2, 3, 7, 8]]

Test Sequences:
[[2, 4, 5], [2, 1, 4, 6], [2, 4, 1], [2, 1, 4, 5, 1, 1]]

Padded Sequences:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 4 5]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 6]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 7 8]]

Padded Test Sequences:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 4 5]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 4 6]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 4 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 4 5 1 1]]


In [23]:
#part of speech tagging


import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords, wordnet

# Download required NLTK resources
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

# Create a Porter stemmer
ps = PorterStemmer()

# Create a WordNet lemmatizer
lemmatizer = WordNetLemmatizer()

# Test the stemmer and lemmatizer
print(ps.stem("playing"))  # Output: play
print(lemmatizer.lemmatize("playing", pos='v'))  # Output: play
print(lemmatizer.lemmatize("fairly", pos='a'))  # Output: fairly
print(lemmatizer.lemmatize("letter", pos='n'))  # Output: letter

# Part-of-speech tagging
text = "I am playing football"
tagged_text = nltk.pos_tag(nltk.word_tokenize(text))
print(tagged_text)


#This code uses NLTK to perform stemming and lemmatization on words, and also demonstrates part-of-speech tagging. Note that lemmatization requires a part-of-speech tag to produce the correct result.

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


play
play
fairly
letter
[('I', 'PRP'), ('am', 'VBP'), ('playing', 'VBG'), ('football', 'NN')]


In [26]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
from tensorflow.keras.layers import Bidirectional,Dropout
from tensorflow.keras import regularizers
nltk.download('stopwords')
nltk.download('punkt')



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [27]:
a="jiyegā maregā maregā\nkaregā bharegā bharegā\nare jiyegā maregā maregā karegā bharegā bharegā\nsūlī chaṛhegā\nlove ke lie sālā kuchh bhī karegā\nare jiyegā maregā …\njāgūṅ sote sote hṇs dūṅ rote rote\ndil ko hārūṅ hārūṅ sīṭī mārūṅ mārūṅ\nye nā jukām hai ye k‌yā nijām hai\njinheṅ nā kām kuchh ye unkā kām hai\nchalegā he he he he\njo ho sahegā sahegā\nāheṅ bharegā bharegā\nuf nahīṅ karegā\nlove ke lie …\npalkeṅ jhapkūṅ jhapkūṅ\nchhat se ṭapkūṅ ṭapkūṅ\nāṇsū piyūṅ piyūṅ mar ke jiyūṅ jiyūṅ\nhe palkeṅ jhap jhap jhapkūṅ\nchhat se ṭap ṭap ṭapkūṅ\nye nā mile kahīṅ ye nā khile kahīṅ\nye aise chīr de jo nā sile kahīṅ\nchalegā hā he he he he\nbāp se laṛegā laṛegā\nghar chhoṛ degā chhoṛegā\ndil meṅ rahegā\nlove ke lie …\nare jiyegā maregā maregā karegā bharegā bharegā\nsūlī chaṛhegā\ndhan ke lie sālā kuchh bhī karegā\ndhan dhan dhan dhanan dhan dhan dhan he dhan dhan dhan\nchorī chorī chorī sīnā jorī jorī\nḍālūṅ dānā dānā gāūṅ gānā gānā\nkamīnā mān lo yā guṅḍā jān lo\nharāmkhor hūṇ yā jo bhī nām lo\nchalegā\nchalega\nbīvī se laṛegā laṛegā\njel meṅ saṛegā saṛegā\nare netā banegā\ndhan ke lie sālā …\nyārī yārī yārī mārā mārī mārī\nronā dhonā dhonā jādū ṭonā ṭonā\nhai ziṅdgī juā jo ho gayā huā\nlagegī badduā chalegā\nsālā kasāī maiṅ galī kā bhāī maiṅ\n-+\ngulām jorū kā nagar jamāī maiṅ banegā\nāg pe chalegā chalegā\npyār se ḍaregā ḍaregā\ndil se bachegā\ndhan ke lie sālā …\nlove ke lie love ke lie\nlove ke lie sālā kuchh bhī karegā\nkuchh bhī karegā sālā kuchh bhī karegā\nā\nkuchh bhī karegā sālā\nkuchh bhī karegā sālā kuchh bhī karegā\nkaregā sālā bharegā\nbharegā sālā maregā\nkaregā bharegā bharegā maregā\nlove ke lie re kuchh bhī karegā\nā masjid ko jāte jāte maiṅ ruk gayā\nkadmoṅ ko chūmne tere maiṅ jhuk gayā\nkuchh bhī karegā sālā kuchh bhī karegā\nna roje namāz na haz ko jāūṅ\npāṇch vaqt us galī meṅ salām bhar āūṅ\nai āheṅ bharegā sālā\njo huā sahegā sālā\nuf nahīṅ karegā sālā\nkaregā bharegā sālā\nbāp se laṛegā sālā\nghar chhoṛ degā sālā\ndil meṅ rahegā sālā\nkuchh bhī karegā sālā kuchh bhī karegā\nkisne pukārā kāfir ye kaisā sabab hai\npūchh lo khudā se love bhī ik mazhab hai\nlove ke lie love ke lie karegā kuchh bhī sālā\nkaregā kuchh …\nlove ke lie love ke lie love ke lie\nkaregā kuchh bhī sālā love ke lie"

In [28]:
corpus=a.lower().split("\n")

In [29]:
corpus

['jiyegā maregā maregā',
 'karegā bharegā bharegā',
 'are jiyegā maregā maregā karegā bharegā bharegā',
 'sūlī chaṛhegā',
 'love ke lie sālā kuchh bhī karegā',
 'are jiyegā maregā …',
 'jāgūṅ sote sote hṇs dūṅ rote rote',
 'dil ko hārūṅ hārūṅ sīṭī mārūṅ mārūṅ',
 'ye nā jukām hai ye k\u200cyā nijām hai',
 'jinheṅ nā kām kuchh ye unkā kām hai',
 'chalegā he he he he',
 'jo ho sahegā sahegā',
 'āheṅ bharegā bharegā',
 'uf nahīṅ karegā',
 'love ke lie …',
 'palkeṅ jhapkūṅ jhapkūṅ',
 'chhat se ṭapkūṅ ṭapkūṅ',
 'āṇsū piyūṅ piyūṅ mar ke jiyūṅ jiyūṅ',
 'he palkeṅ jhap jhap jhapkūṅ',
 'chhat se ṭap ṭap ṭapkūṅ',
 'ye nā mile kahīṅ ye nā khile kahīṅ',
 'ye aise chīr de jo nā sile kahīṅ',
 'chalegā hā he he he he',
 'bāp se laṛegā laṛegā',
 'ghar chhoṛ degā chhoṛegā',
 'dil meṅ rahegā',
 'love ke lie …',
 'are jiyegā maregā maregā karegā bharegā bharegā',
 'sūlī chaṛhegā',
 'dhan ke lie sālā kuchh bhī karegā',
 'dhan dhan dhan dhanan dhan dhan dhan he dhan dhan dhan',
 'chorī chorī chorī sīnā jorī

In [30]:
b=Tokenizer(num_words=100)
b.fit_on_texts(a)

In [31]:
b

In [32]:
b.word_counts

OrderedDict([('j', 34),
             ('i', 52),
             ('y', 25),
             ('e', 186),
             ('g', 98),
             ('ā', 207),
             ('m', 41),
             ('a', 154),
             ('r', 89),
             ('k', 93),
             ('b', 43),
             ('h', 164),
             ('s', 52),
             ('ū', 28),
             ('l', 86),
             ('ī', 48),
             ('c', 39),
             ('ṛ', 12),
             ('o', 50),
             ('v', 16),
             ('u', 32),
             ('…', 6),
             ('ṅ', 42),
             ('t', 11),
             ('ṇ', 4),
             ('d', 32),
             ('ṭ', 8),
             ('n', 47),
             ('\u200c', 1),
             ('f', 3),
             ('p', 21),
             ('ḍ', 4),
             ('z', 4),
             ('q', 1)])

In [33]:
tn=Tokenizer()
tn.fit_on_texts(corpus)

In [34]:
totalwords=len(tn.word_index)+1

In [35]:
print(totalwords)
print(tn.word_index)

150
{'karegā': 1, 'sālā': 2, 'ke': 3, 'kuchh': 4, 'bhī': 5, 'lie': 6, 'bharegā': 7, 'love': 8, 'dhan': 9, 'he': 10, 'maregā': 11, 'se': 12, 'ye': 13, '…': 14, 'hai': 15, 'chalegā': 16, 'nā': 17, 'jo': 18, 'laṛegā': 19, 'maiṅ': 20, 'jiyegā': 21, 'are': 22, 'dil': 23, 'ko': 24, 'meṅ': 25, 'lo': 26, 'sahegā': 27, 'jhapkūṅ': 28, 'ṭapkūṅ': 29, 'kahīṅ': 30, 'chorī': 31, 'yārī': 32, 'gayā': 33, 'sūlī': 34, 'chaṛhegā': 35, 'sote': 36, 'rote': 37, 'hārūṅ': 38, 'mārūṅ': 39, 'kām': 40, 'ho': 41, 'āheṅ': 42, 'uf': 43, 'nahīṅ': 44, 'palkeṅ': 45, 'chhat': 46, 'piyūṅ': 47, 'jiyūṅ': 48, 'jhap': 49, 'ṭap': 50, 'bāp': 51, 'ghar': 52, 'chhoṛ': 53, 'degā': 54, 'rahegā': 55, 'jorī': 56, 'dānā': 57, 'gānā': 58, 'yā': 59, 'saṛegā': 60, 'banegā': 61, 'mārī': 62, 'dhonā': 63, 'ṭonā': 64, 'huā': 65, 'galī': 66, 'kā': 67, 'ḍaregā': 68, 'ā': 69, 'jāte': 70, 'na': 71, 'jāgūṅ': 72, 'hṇs': 73, 'dūṅ': 74, 'sīṭī': 75, 'jukām': 76, 'k\u200cyā': 77, 'nijām': 78, 'jinheṅ': 79, 'unkā': 80, 'āṇsū': 81, 'mar': 82, 'mile': 8

In [36]:
input_sequences=[]
for line in corpus:
    token_list=tn.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)
        print(n_gram_sequence)

[21, 11]
[21, 11, 11]
[1, 7]
[1, 7, 7]
[22, 21]
[22, 21, 11]
[22, 21, 11, 11]
[22, 21, 11, 11, 1]
[22, 21, 11, 11, 1, 7]
[22, 21, 11, 11, 1, 7, 7]
[34, 35]
[8, 3]
[8, 3, 6]
[8, 3, 6, 2]
[8, 3, 6, 2, 4]
[8, 3, 6, 2, 4, 5]
[8, 3, 6, 2, 4, 5, 1]
[22, 21]
[22, 21, 11]
[22, 21, 11, 14]
[72, 36]
[72, 36, 36]
[72, 36, 36, 73]
[72, 36, 36, 73, 74]
[72, 36, 36, 73, 74, 37]
[72, 36, 36, 73, 74, 37, 37]
[23, 24]
[23, 24, 38]
[23, 24, 38, 38]
[23, 24, 38, 38, 75]
[23, 24, 38, 38, 75, 39]
[23, 24, 38, 38, 75, 39, 39]
[13, 17]
[13, 17, 76]
[13, 17, 76, 15]
[13, 17, 76, 15, 13]
[13, 17, 76, 15, 13, 77]
[13, 17, 76, 15, 13, 77, 78]
[13, 17, 76, 15, 13, 77, 78, 15]
[79, 17]
[79, 17, 40]
[79, 17, 40, 4]
[79, 17, 40, 4, 13]
[79, 17, 40, 4, 13, 80]
[79, 17, 40, 4, 13, 80, 40]
[79, 17, 40, 4, 13, 80, 40, 15]
[16, 10]
[16, 10, 10]
[16, 10, 10, 10]
[16, 10, 10, 10, 10]
[18, 41]
[18, 41, 27]
[18, 41, 27, 27]
[42, 7]
[42, 7, 7]
[43, 44]
[43, 44, 1]
[8, 3]
[8, 3, 6]
[8, 3, 6, 14]
[45, 28]
[45, 28, 28]
[46, 12]


In [37]:
print(input_sequences)

[[21, 11], [21, 11, 11], [1, 7], [1, 7, 7], [22, 21], [22, 21, 11], [22, 21, 11, 11], [22, 21, 11, 11, 1], [22, 21, 11, 11, 1, 7], [22, 21, 11, 11, 1, 7, 7], [34, 35], [8, 3], [8, 3, 6], [8, 3, 6, 2], [8, 3, 6, 2, 4], [8, 3, 6, 2, 4, 5], [8, 3, 6, 2, 4, 5, 1], [22, 21], [22, 21, 11], [22, 21, 11, 14], [72, 36], [72, 36, 36], [72, 36, 36, 73], [72, 36, 36, 73, 74], [72, 36, 36, 73, 74, 37], [72, 36, 36, 73, 74, 37, 37], [23, 24], [23, 24, 38], [23, 24, 38, 38], [23, 24, 38, 38, 75], [23, 24, 38, 38, 75, 39], [23, 24, 38, 38, 75, 39, 39], [13, 17], [13, 17, 76], [13, 17, 76, 15], [13, 17, 76, 15, 13], [13, 17, 76, 15, 13, 77], [13, 17, 76, 15, 13, 77, 78], [13, 17, 76, 15, 13, 77, 78, 15], [79, 17], [79, 17, 40], [79, 17, 40, 4], [79, 17, 40, 4, 13], [79, 17, 40, 4, 13, 80], [79, 17, 40, 4, 13, 80, 40], [79, 17, 40, 4, 13, 80, 40, 15], [16, 10], [16, 10, 10], [16, 10, 10, 10], [16, 10, 10, 10, 10], [18, 41], [18, 41, 27], [18, 41, 27, 27], [42, 7], [42, 7, 7], [43, 44], [43, 44, 1], [8, 

In [38]:
max_sequence_len=max([len(x) for x in input_sequences])
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))

In [39]:
print(len(input_sequences))
print(max_sequence_len)

344
11


In [40]:
xs,labels=input_sequences[:,:-1],input_sequences[:,-1]
ys=tf.keras.utils.to_categorical(labels,num_classes=totalwords)

In [41]:
model=Sequential()
model.add(Embedding(totalwords,100,input_length=max_sequence_len-1))
model.add(Bidirectional(LSTM(20,return_sequences=True)))
model.add(Dropout(0.2))
model.add(LSTM(100))

model.add(Dense(totalwords,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])



In [ ]:
ak=model.fit(xs,ys,epochs=100,verbose=1)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 7s 19ms/step - accuracy: 0.0372 - loss: 5.0041
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0447 - loss: 4.8925
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0543 - loss: 4.5034
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0541 - loss: 4.3487
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1039 - loss: 4.1913
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.0870 - loss: 4.2923
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0543 - loss: 4.1961
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.0885 - loss: 4.1096
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1097 - loss: 3.9443
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.1178 - loss: 3.8159
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.1446 - loss: 3.6775
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step

In [ ]:
evaluated=model.evaluate(xs,ys,verbose=0)

In [ ]:
print(evaluated)

In [ ]:
from os import pread
seed_text="love ke lie"
next_words=10
for _ in range(next_words):
    token_list=tn.texts_to_sequences([seed_text])[0]
    token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding='post')
    predicted_probs=model.predict(token_list,verbose=0)
    predicted=np.argmax(predicted_probs,axis=-1)
    output_word=""
    for word,index in tn.word_index.items():
        if index==predicted:
            output_word=word
            break
    seed_text+=" "+output_word
print(seed_text)



